include ~/.cache/wal/colors-kitty.conf
shell fish

background_opacity 0.5
background_blur 1


font_family Fantasque Sans Mono
font_size 17
active_tab_foreground #ffffff
inactive_tab_foreground #888888


cursor_shape block
cursor #cccccc
cursor_trail 4